version: 1.5.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '1.5.8.0'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- pwsh: nuget restore src/Rhyous.SimplePluginLoader.sln
configuration:
  Release
build:
  project: src/Rhyous.SimplePluginLoader.sln
  verbosity: minimal
test:
  categories:
    except:
    - slow
    - LocalOnly
nuget:
  disable_publish_on_pr: true
artifacts:
  - path: 'src\Rhyous.SimplePluginLoader\**\*.nupkg;src\Rhyous.SimplePluginLoader.Autofac\**\*.nupkg;'
deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: 0atBWZHBxA1tMMSATgnvZ3ew3l38cESi/pSrosX0j8OevgbxgA9z75qtyBnCfYfz